name: Publish to npm

on:
  push:
    branches:
      - main # Trigger on changes to the main branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 
          registry-url: 'https://registry.npmjs.org/'

      # Step 3: Authenticate with npm
      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 6: Publish to npm
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
