name: Publish Package

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tag pushes (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the desired Node.js versio (e.g., '16')

      # Step 3: Authenticate with npm
      - name: Authenticate with npm
        run: npm config set '//registry.npmjs.org/:_authToken' ${{ secrets.NPM_TOKEN }}

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Clean the build directory (if needed) and run the build script
      - name: Run build
        run: npm run clean && npm run build

      # Step 6: Version bump and publish to npm
      - name: Version bump and publish
        run: |
          npm version patch  # Increase patch version
          npm run build      # Run the build again to ensure it’s fresh
          npm publish        # Publish the package to npm
